server:
 port: 8080

springdoc:
 swagger-ui:
  path= /swagger-ui.html
# use h2 database on this website when server is start - http://localhost:8080/h2-console/
spring: 
 application:
  name: "accounts"
 profiles:
  active: "prod"

 datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: ''

#enalble h2 console
 h2:
  console:
   enabled: true
  
 jpa:
  database-plateform: org.hibernate.dialect.H2Dialect
  hibernate:
   ddl-auto: update
#update mean to create table if not created and print all sql query using show-sql
  show-sql: true
 config:
  import: "optional:configserver:http://localhost:8071/"
eureka:
 instance:
  preferIpAddress: true #register as hostname
 client:
  fetchRegistry: true
  registerWithEureka: true
  serviceUrl:
   defaultZone: http://localhost:8070/eureka/

management:
 endpoints:
  web:
   exposure:
    include: "*"
 endpoint:
  shutdown:
   enabled: true 	#access:unrestricted 
 info:
  env:
   enabled: true
   
endpoints:
 shutdown:
  enabled: true
   
info:
 app:
  name: "accounts"
  description: "Learning M.S Application"
  version: "1.0.0"
 
# config: 
#  import:
#   - "application_qa.yml"
#   - "application_prod.yml"
# profiles:
#  active:
#   - "qa"
#build:
# version: "3.0"
# 
#accounts:
# message: "Welcome to Vaibhav accounts related local API's"
# contactDetails:
#  name: "Vaibhav Garg"
#  email: "Vaibhavgarg3210@gmail.com"
# onCallSupport:
#  - (XXXXXXXXXXX)
#  - (XXXXXXXXXXX)