spring:
 application:
  name: "configserver"
 profiles:
  active: native # for file related use native and for git related use git
 cloud:
  config:
   server:
    native:
     #search-locations: classpath:/config # use for same classpath
     search-locations: classpath:/config
     #git:
     # uri:  use for git config
     #default-label:main you can choose branch
     #timeout:5 after 5 sec close
     #clone-on-start:true clone the repo file into local system when start application
     #force-pull:true override local change it pull latest pull from master 
management:
 endpoints:
  web:
   exposure:
    include: "*"
 health:
  readiness-state:
   enabled: true
  liveness-state:
   enabled: true
 endpoint:
  health:
   probes: 
    enabled: true
 metrics:  # define the matrics with microservices
  export:
   prometheus:
    enabled: true
  tags:
   application: ${spring.application.name}

server:
 port: 8071