build:
 version: "3.0"
 
accounts:
 message: "Welcome to Vaibhav great accounts related localss API's"
 contactDetails:
  name: "Vaibhav Garg"
  email: "Vaibhavgarg3210@gmail.com"
 onCallSupport:
  - (XXXXXXXXXXX)
  - (XXXXXXXXXXX)