build:
 version: "3.0"
 
loans:
 message: "Welcome to Vaibhav loans related local API's"
 contactDetails:
  name: "Vaibhav Garg"
  email: "Vaibhavgarg3210@gmail.com"
 onCallSupport:
  - (XXXXXXXXXXX)
  - (XXXXXXXXXXX)